<?php

return [
    'legal_profiles' => [
        'pflegeversicherung' => [
            'title' => 'Pflegeversicherung nach dem SGB XI',
            'body' => 'Das Elfte Buch Sozialgesetzbuch (SGB XI) regelt die soziale Pflegeversicherung. Ob eine Leistung im Einzelfall bewilligt wird, entscheidet die Pflegekasse anhand des Pflegegrades, der Versorgungsform und der gesetzlichen Voraussetzungen.',
        ],
        'krankenversicherung' => [
            'title' => 'Krankenversicherung nach dem SGB V',
            'body' => 'Das Fünfte Buch Sozialgesetzbuch (SGB V) regelt Leistungen der gesetzlichen Krankenversicherung. Häufig sind eine ärztliche Verordnung, eine medizinische Begründung und die Entscheidung der Krankenkasse erforderlich.',
        ],
        'arbeit_und_pflege' => [
            'title' => 'Freistellung und Absicherung im Beruf',
            'body' => 'Pflegezeitgesetz und Familienpflegezeitgesetz schaffen unter bestimmten Voraussetzungen Möglichkeiten zur Freistellung oder Arbeitszeitreduzierung. Betriebsgröße, Ankündigungsfristen und Nachweise können dabei entscheidend sein.',
        ],
        'sozialhilfe' => [
            'title' => 'Hilfe zur Pflege nach dem SGB XII',
            'body' => 'Das Zwölfte Buch Sozialgesetzbuch (SGB XII) kann ergänzende Hilfe zur Pflege vorsehen, wenn notwendige Pflegekosten nicht durch eigenes Einkommen, Vermögen oder vorrangige Leistungen gedeckt werden. Zuständig ist der Sozialhilfeträger.',
        ],
        'vertrag' => [
            'title' => 'Vertrag und Kosten schriftlich prüfen',
            'body' => 'Je nach Wohn- und Leistungsform können das Bürgerliche Gesetzbuch und das Wohn- und Betreuungsvertragsgesetz gelten. Entscheidend sind der konkrete Vertrag, die ausgewiesenen Leistungen, Kosten, Kündigungsregeln und mögliche Preisanpassungen.',
        ],
        'heimkosten' => [
            'title' => 'Pflegeleistung und Eigenkosten unterscheiden',
            'body' => 'Bei stationärer Pflege regelt das SGB XI den Anteil der Pflegeversicherung. Unterkunft, Verpflegung, Investitionskosten und weitere Entgelte folgen zusätzlichen gesetzlichen und vertraglichen Regeln und müssen getrennt ausgewiesen werden.',
        ],
        'vorsorge' => [
            'title' => 'Vertretungsmacht entsteht nicht automatisch',
            'body' => 'Eine Vorsorgevollmacht richtet sich vor allem nach dem Bürgerlichen Gesetzbuch. Umfang, Form und Wirksamkeit hängen vom Inhalt der Vollmacht ab; für einzelne Geschäfte können besondere Formvorgaben gelten.',
        ],
        'widerspruch' => [
            'title' => 'Frist und Rechtsbehelfsbelehrung beachten',
            'body' => 'Gegen einen belastenden Bescheid kann grundsätzlich Widerspruch möglich sein. Maßgeblich sind die Rechtsbehelfsbelehrung, die dort genannte Frist und der nachweisbare Eingang bei der zuständigen Stelle.',
        ],
        'barrierefreiheit' => [
            'title' => 'Barrierefreiheit hängt vom Anwendungsbereich ab',
            'body' => 'Anforderungen können sich unter anderem aus dem Behindertengleichstellungsrecht, dem Baurecht und besonderen Vorschriften für Einrichtungen ergeben. Nicht jede bestehende Wohnung oder private Dienstleistung muss automatisch dieselben Vorgaben erfüllen.',
        ],
        'hospiz_palliativ' => [
            'title' => 'Versorgung am Lebensende',
            'body' => 'Ansprüche auf Hospiz- und Palliativversorgung ergeben sich vor allem aus dem SGB V; in Pflegeeinrichtungen greifen zusätzlich Regelungen des SGB XI. Welche Versorgung passt, wird nach dem individuellen medizinischen und pflegerischen Bedarf entschieden.',
        ],
        'orientation' => [
            'title' => 'Der Begriff allein begründet noch keinen Anspruch',
            'body' => 'Nicht jeder Pflegebegriff bezeichnet eine eigenständige gesetzliche Leistung. Für die Kostenübernahme sind der konkrete Bedarf, der zuständige Kostenträger, eine mögliche Verordnung oder ein Bescheid und die Vertragsbedingungen entscheidend.',
        ],
        'sgb_v' => [
            'title' => 'Was regelt das SGB V?',
            'body' => 'Das SGB V ist die zentrale gesetzliche Grundlage der gesetzlichen Krankenversicherung. Es regelt unter anderem ärztliche Behandlung, häusliche Krankenpflege, Hilfsmittel sowie Hospiz- und Palliativleistungen.',
        ],
        'sgb_xi' => [
            'title' => 'Was regelt das SGB XI?',
            'body' => 'Das SGB XI ist die zentrale gesetzliche Grundlage der sozialen Pflegeversicherung. Es regelt Pflegebedürftigkeit, Pflegegrade, Beratung, häusliche und stationäre Leistungen sowie Qualitätsanforderungen.',
        ],
    ],
    'terms' => [
        'ambulante-pflege' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Herr Klein benötigt morgens Hilfe beim Waschen und Anziehen. Ein ambulanter Pflegedienst kommt an vereinbarten Tagen zu ihm nach Hause.'],
        'behandlungspflege' => ['legal_profile' => 'krankenversicherung', 'example' => 'Nach einer Operation verordnet die Ärztin regelmäßige Verbandswechsel, die ein Pflegedienst zu Hause durchführt.'],
        'entlastungsbetrag' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Frau Berger nutzt ein anerkanntes Betreuungsangebot und reicht die Rechnung anschließend bei ihrer Pflegekasse ein.'],
        'kurzzeitpflege' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Nach dem Krankenhausaufenthalt kann Herr Vogel noch nicht allein zu Hause leben und zieht vorübergehend in eine Kurzzeitpflegeeinrichtung.'],
        'pflegeberatung' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Eine Tochter vereinbart nach dem Pflegegradbescheid einen Beratungstermin, um Pflegegeld, Pflegedienst und Tagespflege miteinander zu vergleichen.'],
        'pflegegeld' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Frau Sommer wird überwiegend von ihrem Sohn zu Hause gepflegt und erhält das Pflegegeld auf ihr eigenes Konto.'],
        'pflegegrad' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Herr Braun kann Medikamente und Körperpflege nicht mehr selbstständig organisieren; diese Einschränkungen werden bei der Begutachtung betrachtet.'],
        'pflegehilfsmittel' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Ein Pflegebett soll das sichere Aufstehen erleichtern. Vor dem Kauf fragt die Familie bei der Pflegekasse nach der Versorgung.'],
        'pflegesachleistung' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Ein zugelassener Pflegedienst übernimmt morgens die Körperpflege und rechnet die vereinbarten Leistungen direkt mit der Pflegekasse ab.'],
        'stationaere-pflege' => ['legal_profile' => 'heimkosten', 'example' => 'Weil die Versorgung zu Hause nicht mehr sicher gelingt, zieht Frau Lehmann dauerhaft in ein Pflegeheim.'],
        'tagespflege' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Herr Schulz besucht zweimal pro Woche eine Tagespflege und verbringt die übrige Zeit weiterhin in seiner Wohnung.'],
        'verhinderungspflege' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Während die pflegende Tochter Urlaub macht, übernimmt für einige Tage ein Pflegedienst die Versorgung ihres Vaters.'],
        'alltagsbegleitung' => ['legal_profile' => 'orientation', 'example' => 'Eine Alltagsbegleiterin geht mit Frau Neumann einkaufen und unterstützt sie dabei, ihren Tagesablauf zu strukturieren.'],
        'angehoerigenpflege' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Zwei Geschwister teilen sich Arzttermine, Einkäufe und die tägliche Unterstützung ihrer Mutter.'],
        'antrag-pflegegrad' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Herr Richter ruft bei seiner Pflegekasse an und erklärt, dass er Leistungen wegen Pflegebedürftigkeit beantragen möchte.'],
        'ausserklinische-intensivpflege' => ['legal_profile' => 'krankenversicherung', 'example' => 'Eine beatmete Person wird nach ärztlicher Verordnung durch speziell qualifizierte Pflegekräfte in einer geeigneten Wohnform versorgt.'],
        'barrierefreiheit' => ['legal_profile' => 'barrierefreiheit', 'example' => 'Ein stufenloser Eingang und eine gut lesbare Beschilderung ermöglichen es einer Rollstuhlnutzerin, die Einrichtung selbstständig zu betreten.'],
        'begutachtung' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Beim Hausbesuch schildert die Familie, wobei täglich Anleitung, Beaufsichtigung oder körperliche Hilfe notwendig ist.'],
        'beratungsbesuch' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Eine Pflegefachperson besucht einen Pflegegeldempfänger zu Hause und bespricht, ob die Versorgung gesichert ist.'],
        'betreutes-wohnen' => ['legal_profile' => 'vertrag', 'example' => 'Frau Krüger mietet eine barrierearme Wohnung und bucht zusätzlich einen Hausnotruf; Pflegeleistungen vereinbart sie bei Bedarf separat.'],
        'demenz' => ['legal_profile' => 'orientation', 'example' => 'Herr Wolf findet bekannte Wege nicht mehr sicher und benötigt Erinnerung bei Mahlzeiten und Medikamenten.'],
        'digitale-pflegeanwendung' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Eine anerkannte App hilft einer pflegebedürftigen Person und ihren Angehörigen, Übungen und Pflegeabläufe zu organisieren.'],
        'eigenanteil' => ['legal_profile' => 'heimkosten', 'example' => 'Im Kostenangebot des Pflegeheims stehen neben dem Anteil für Pflege auch Unterkunft, Verpflegung und Investitionskosten.'],
        'einrichtungseinheitlicher-eigenanteil' => ['legal_profile' => 'heimkosten', 'example' => 'Zwei Bewohner derselben Einrichtung haben unterschiedliche Pflegegrade, zahlen aber grundsätzlich denselben pflegebedingten Eigenanteil der Einrichtung.'],
        'entlassmanagement' => ['legal_profile' => 'krankenversicherung', 'example' => 'Vor der Krankenhausentlassung werden Pflegedienst, Hilfsmittel und notwendige Anschlussbehandlungen organisiert.'],
        'ersatzpflege' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Fällt die private Pflegeperson krankheitsbedingt aus, übernimmt vorübergehend eine andere geeignete Person die Pflege.'],
        'familienpflegezeit' => ['legal_profile' => 'arbeit_und_pflege', 'example' => 'Eine Beschäftigte reduziert ihre Wochenarbeitszeit für einen längeren Zeitraum, um ihren Vater zu pflegen.'],
        'fahrdienst' => ['legal_profile' => 'krankenversicherung', 'example' => 'Eine Tagespflege holt einen Gast morgens ab; für eine medizinisch notwendige Krankenfahrt gelten dagegen andere Voraussetzungen.'],
        'grundpflege' => ['legal_profile' => 'orientation', 'example' => 'Ein Pflegedienst unterstützt Herrn König beim Waschen, Anziehen und bei der Nahrungsaufnahme.'],
        'hausnotruf' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Frau Albrecht trägt einen Notrufknopf und kann nach einem Sturz eine ständig erreichbare Zentrale alarmieren.'],
        'hilfe-zur-pflege' => ['legal_profile' => 'sozialhilfe', 'example' => 'Die Leistungen der Pflegeversicherung und das eigene Einkommen reichen für notwendige Heimkosten nicht aus; der Sozialhilfeträger prüft ergänzende Hilfe.'],
        'hilfsmittel' => ['legal_profile' => 'krankenversicherung', 'example' => 'Eine Ärztin empfiehlt einen Rollator; die Krankenkasse prüft anschließend die Versorgung über einen Vertragspartner.'],
        'hospiz' => ['legal_profile' => 'hospiz_palliativ', 'example' => 'Ein schwerstkranker Mensch zieht in ein stationäres Hospiz, weil die Versorgung zu Hause nicht mehr möglich ist.'],
        'investitionskosten' => ['legal_profile' => 'heimkosten', 'example' => 'Auf der Heimrechnung werden Kosten für Gebäude und Ausstattung getrennt von Pflege, Unterkunft und Verpflegung ausgewiesen.'],
        'kombinationsleistung' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Ein Pflegedienst übernimmt einen Teil der Pflege; für den selbst organisierten Anteil wird anteilig Pflegegeld gezahlt.'],
        'krankenkasse-und-pflegekasse' => ['legal_profile' => 'orientation', 'example' => 'Die Krankenkasse prüft eine ärztlich verordnete Wundversorgung, während die Pflegekasse über Pflegegeld entscheidet.'],
        'kurzzeitige-arbeitsverhinderung' => ['legal_profile' => 'arbeit_und_pflege', 'example' => 'Nach einem plötzlichen Sturz der Mutter bleibt ein Beschäftigter kurzfristig der Arbeit fern, um die Versorgung zu organisieren.'],
        'medizinischer-dienst' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Die Pflegekasse beauftragt den Medizinischen Dienst, die Selbstständigkeit einer versicherten Person zu begutachten.'],
        'nachtpflege' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Eine pflegebedürftige Person verbringt mehrere Nächte pro Woche in einer Einrichtung und wird tagsüber zu Hause versorgt.'],
        'palliativpflege' => ['legal_profile' => 'hospiz_palliativ', 'example' => 'Bei einer unheilbaren Erkrankung stehen Schmerzlinderung, Symptomkontrolle und Lebensqualität im Mittelpunkt der Versorgung.'],
        'pflegebeduerftigkeit' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Wegen dauerhafter gesundheitlicher Einschränkungen benötigt Frau Brandt regelmäßig Hilfe und Anleitung im Alltag.'],
        'pflegeheim' => ['legal_profile' => 'heimkosten', 'example' => 'Eine Einrichtung bietet dauerhaft Unterkunft, Verpflegung, Pflege und Betreuung auf Grundlage eines Heimvertrags an.'],
        'pflegekasse' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Der Antrag auf Pflegeleistungen wird an die Pflegekasse geschickt, die organisatorisch bei der Krankenkasse angesiedelt ist.'],
        'pflegekurse' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Ein Angehöriger lernt in einem Pflegekurs rückenschonende Handgriffe und den sicheren Umgang mit Hilfsmitteln.'],
        'pflegeperson' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Eine Nachbarin unterstützt regelmäßig unentgeltlich einen pflegebedürftigen Menschen in dessen Wohnung.'],
        'pflegeplan' => ['legal_profile' => 'orientation', 'example' => 'Pflegefachkräfte dokumentieren Ziele, vereinbarte Maßnahmen und Beobachtungen und passen die Planung bei Veränderungen an.'],
        'pflegestuetzpunkt' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Eine Familie erhält im Pflegestützpunkt eine trägerübergreifende Orientierung zu Anträgen und Angeboten vor Ort.'],
        'pflegeunterstuetzungsgeld' => ['legal_profile' => 'arbeit_und_pflege', 'example' => 'Während einer kurzfristigen Freistellung beantragt ein Angehöriger eine Lohnersatzleistung bei der Pflegekasse der pflegebedürftigen Person.'],
        'pflegevertrag' => ['legal_profile' => 'vertrag', 'example' => 'Vor dem Start eines Pflegedienstes prüft die Familie Leistungsumfang, Preise, private Zusatzkosten und Kündigungsfrist.'],
        'pflege-wohngemeinschaft' => ['legal_profile' => 'vertrag', 'example' => 'Mehrere pflegebedürftige Menschen wohnen zusammen und organisieren Pflege und Alltagsunterstützung gemeinschaftlich.'],
        'pflegezeit' => ['legal_profile' => 'arbeit_und_pflege', 'example' => 'Eine Arbeitnehmerin lässt sich für mehrere Monate vollständig freistellen, um einen nahen Angehörigen zu pflegen.'],
        'qualitaetspruefung' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Eine Prüfstelle kontrolliert in einer Pflegeeinrichtung unter anderem Pflegeprozesse, Ergebnisse und die Einhaltung von Qualitätsanforderungen.'],
        'sapv' => ['legal_profile' => 'hospiz_palliativ', 'example' => 'Ein spezialisiertes Team betreut einen schwerkranken Menschen mit komplexen Symptomen in seiner Wohnung.'],
        'sgb-v' => ['legal_profile' => 'sgb_v', 'example' => 'Eine ärztlich verordnete häusliche Krankenpflege wird nach den Regeln des SGB V von der Krankenkasse geprüft.'],
        'sgb-xi' => ['legal_profile' => 'sgb_xi', 'example' => 'Pflegegrad, Pflegegeld und Pflegesachleistungen gehören zu den Themen, deren Grundlagen im SGB XI geregelt sind.'],
        'uebergangspflege' => ['legal_profile' => 'krankenversicherung', 'example' => 'Kann nach einer Behandlung keine sofortige Anschlussversorgung organisiert werden, bleibt eine Patientin vorübergehend im Krankenhaus versorgt.'],
        'umwandlungsanspruch' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Ein Teil eines nicht genutzten Sachleistungsbudgets wird unter den gesetzlichen Voraussetzungen für anerkannte Alltagsunterstützung eingesetzt.'],
        'vorsorgevollmacht' => ['legal_profile' => 'vorsorge', 'example' => 'Frau Peters bevollmächtigt ihre Tochter schriftlich, später bestimmte Gesundheits- und Behördenangelegenheiten für sie zu regeln.'],
        'widerspruch-pflegegrad' => ['legal_profile' => 'widerspruch', 'example' => 'Nach Durchsicht des Gutachtens beschreibt die Familie im Widerspruch konkret, welche täglichen Einschränkungen nicht berücksichtigt wurden.'],
        'wohnraumanpassung' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Vor dem Umbau einer Dusche beantragt eine Familie bei der Pflegekasse einen Zuschuss zur Wohnraumanpassung.'],
        'wohngruppenzuschlag' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Die Mitglieder einer Pflege-WG beauftragen gemeinsam eine Präsenzkraft und lassen die Voraussetzungen von ihren Pflegekassen prüfen.'],
        'zusaetzliche-betreuungskraft' => ['legal_profile' => 'pflegeversicherung', 'example' => 'Eine Betreuungskraft liest mit Heimbewohnern, begleitet Spaziergänge und bietet gemeinsame Beschäftigungen an.'],
    ],
];
