<?php

$bmgHomeCare = 'https://www.bundesgesundheitsministerium.de/pflege-zu-hause/';
$bmgSupport = 'https://www.bundesgesundheitsministerium.de/pflege-zu-hause/weitere-leistungen-und-angebote-zur-unterstuetzung-im-alltag';
$bmgNeed = 'https://www.bundesgesundheitsministerium.de/themen/pflege/online-ratgeber-pflege/pflegebeduerftig-was-nun/pflegebeduerftigkeit';
$bmgApplication = 'https://www.bundesgesundheitsministerium.de/themen/pflege/online-ratgeber-pflege/pflegebeduerftig-was-nun';
$bmgHome = 'https://www.bundesgesundheitsministerium.de/themen/pflege/online-ratgeber-pflege/leistungen-der-pflegeversicherung/vollstationaere-pflege-im-heim';
$bmgQuality = 'https://www.bundesgesundheitsministerium.de/themen/pflege/online-ratgeber-pflege/qualitaet-transparenz-hilfe-bei-problemen/qualitaetspruefungen';
$bmgWg = 'https://www.bundesgesundheitsministerium.de/themen/pflege/online-ratgeber-pflege/leistungen-der-pflegeversicherung/pflege-wohngemeinschaften-und-andere-alternative-wohnformen';
$checkedAt = '2026-07-16';

return [
    'alltagsbegleitung' => [
        'title' => 'Alltagsbegleitung', 'letter' => 'A',
        'summary' => 'Unterstützung bei Tagesstruktur, sozialen Kontakten und alltäglichen Aufgaben.',
        'intro' => 'Alltagsbegleiterinnen und Alltagsbegleiter helfen pflegebedürftigen Menschen, ihren Alltag möglichst selbstbestimmt zu gestalten. Dazu können Gespräche, Spaziergänge, gemeinsames Einkaufen oder Beschäftigungsangebote gehören.',
        'sections' => [['title' => 'Ist das Pflege?', 'body' => 'Alltagsbegleitung ersetzt keine medizinische Behandlungspflege. Welche Tätigkeiten angeboten und über die Pflegeversicherung abgerechnet werden können, hängt von Qualifikation, Zulassung und Anerkennung des Angebots ab.']],
        'tip' => 'Vor der Buchung Leistungen, Anerkennung, Stundensatz und mögliche Abrechnung über den Entlastungsbetrag klären.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Angebote zur Unterstützung im Alltag', 'url' => $bmgSupport]],
        'related' => ['entlastungsbetrag', 'zusaetzliche-betreuungskraft', 'ambulante-pflege'], 'checked_at' => $checkedAt,
    ],
    'angehoerigenpflege' => [
        'title' => 'Angehörigenpflege', 'letter' => 'A',
        'summary' => 'Pflege und Unterstützung durch Familienmitglieder oder andere nahestehende Personen.',
        'intro' => 'Viele pflegebedürftige Menschen werden ganz oder teilweise von Angehörigen zu Hause versorgt. Die Pflege kann mit professionellen Diensten, Tagespflege und Entlastungsangeboten kombiniert werden.',
        'sections' => [['title' => 'Entlastung gehört dazu', 'body' => 'Pflegeberatung, Pflegekurse, Verhinderungspflege und weitere Unterstützungsangebote können helfen, Überlastung zu vermeiden. Zuständigkeiten sollten möglichst auf mehrere Personen verteilt werden.']],
        'tip' => 'Frühzeitig einen Notfallplan erstellen und klären, wer bei Krankheit oder Urlaub die Versorgung übernimmt.',
        'sources' => [['label' => 'Sozialgesetzbuch XI: Begriff der Pflegeperson', 'url' => 'https://www.gesetze-im-internet.de/sgb_11/__19.html']],
        'related' => ['pflegeperson', 'pflegekurse', 'verhinderungspflege'], 'checked_at' => $checkedAt,
    ],
    'antrag-pflegegrad' => [
        'title' => 'Antrag auf Pflegegrad', 'letter' => 'A',
        'summary' => 'Antrag bei der Pflegekasse, mit dem das Verfahren zur Feststellung der Pflegebedürftigkeit beginnt.',
        'intro' => 'Leistungen der Pflegeversicherung müssen grundsätzlich beantragt werden. Der Antrag kann zunächst formlos bei der Pflegekasse gestellt werden; anschließend wird eine Begutachtung veranlasst.',
        'sections' => [['title' => 'Was passiert danach?', 'body' => 'Die Pflegekasse beauftragt den Medizinischen Dienst oder eine andere zuständige Begutachtungsstelle. Nach der Prüfung folgt ein schriftlicher Bescheid mit dem festgestellten Pflegegrad oder einer Ablehnung.']],
        'tip' => 'Das Datum des ersten Antrags dokumentieren und vor der Begutachtung den Hilfebedarf im Alltag notieren.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Antragsverfahren', 'url' => $bmgApplication]],
        'related' => ['begutachtung', 'pflegegrad', 'widerspruch-pflegegrad'], 'checked_at' => $checkedAt,
    ],
    'ausserklinische-intensivpflege' => [
        'title' => 'Außerklinische Intensivpflege', 'letter' => 'A',
        'summary' => 'Besonders aufwendige medizinische und pflegerische Versorgung außerhalb eines Krankenhauses.',
        'intro' => 'Außerklinische Intensivpflege richtet sich an schwer erkrankte Menschen mit einem sehr hohen medizinischen Pflegebedarf, beispielsweise bei Beatmung. Sie kann zu Hause, in einer Wohneinheit oder in einer spezialisierten Einrichtung erfolgen.',
        'sections' => [['title' => 'Besondere Voraussetzungen', 'body' => 'Die Versorgung wird ärztlich verordnet und folgt besonderen gesetzlichen, personellen und qualitativen Anforderungen. Eine allgemeine ambulante Pflegeleistung ist damit nicht gleichzusetzen.']],
        'tip' => 'Versorgungsform, ärztliche Betreuung, Notfallkonzept und Kostenübernahme vor Beginn schriftlich abstimmen.',
        'sources' => [['label' => 'Sozialgesetzbuch V: Außerklinische Intensivpflege', 'url' => 'https://www.gesetze-im-internet.de/sgb_5/__37c.html']],
        'related' => ['behandlungspflege', 'ambulante-pflege', 'pflegevertrag'], 'checked_at' => $checkedAt,
    ],
    'barrierefreiheit' => [
        'title' => 'Barrierefreiheit', 'letter' => 'B',
        'summary' => 'Gestaltung, die Menschen mit Behinderungen eine möglichst selbstständige Nutzung ermöglicht.',
        'intro' => 'Barrierefreiheit kann stufenlose Zugänge, ausreichend breite Türen, geeignete Aufzüge, verständliche Orientierung und nutzbare Sanitärbereiche umfassen. Der konkrete Bedarf ist von Person zu Person verschieden.',
        'sections' => [['title' => 'Nicht nur rollstuhlgerecht', 'body' => 'Auch Seh-, Hör- oder kognitive Einschränkungen müssen berücksichtigt werden. Eine allgemeine Werbeaussage sollte deshalb immer anhand der persönlichen Anforderungen geprüft werden.']],
        'tip' => 'Bei einer Besichtigung die tatsächlich benötigten Wege, Türen, Bäder und Orientierungshilfen selbst prüfen.',
        'sources' => [['label' => 'Behindertengleichstellungsgesetz: Definition der Barrierefreiheit', 'url' => 'https://www.gesetze-im-internet.de/bgg/__4.html']],
        'related' => ['wohnraumanpassung', 'pflegehilfsmittel', 'betreutes-wohnen'], 'checked_at' => $checkedAt,
    ],
    'begutachtung' => [
        'title' => 'Begutachtung', 'letter' => 'B',
        'summary' => 'Prüfung des Hilfebedarfs zur Feststellung eines Pflegegrades.',
        'intro' => 'Bei der Begutachtung wird untersucht, wie selbstständig ein Mensch seinen Alltag bewältigen kann. Körperliche, kognitive und psychische Beeinträchtigungen werden nach einem festgelegten Verfahren berücksichtigt.',
        'sections' => [['title' => 'Wer begutachtet?', 'body' => 'Bei gesetzlich Versicherten beauftragt die Pflegekasse in der Regel den Medizinischen Dienst. Für privat Versicherte ist regelmäßig Medicproof zuständig. Das Ergebnis wird in einem Gutachten festgehalten.']],
        'tip' => 'Eine vertraute Person kann teilnehmen. Hilfsmittel, Medikamentenplan und Notizen zum täglichen Unterstützungsbedarf bereitlegen.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Begutachtung', 'url' => 'https://www.bundesgesundheitsministerium.de/service/begriffe-von-a-z/b/begutachtung-pflegeversicherung']],
        'related' => ['antrag-pflegegrad', 'pflegegrad', 'medizinischer-dienst'], 'checked_at' => $checkedAt,
    ],
    'beratungsbesuch' => [
        'title' => 'Beratungsbesuch nach § 37 Absatz 3 SGB XI', 'letter' => 'B',
        'summary' => 'Regelmäßige Beratung zu Hause bei selbst organisierter Pflege.',
        'intro' => 'Wer Pflegegeld bezieht, muss abhängig vom Pflegegrad in bestimmten Abständen einen Beratungsbesuch abrufen. Er soll die Qualität der häuslichen Pflege sichern und praktische Unterstützung geben.',
        'sections' => [['title' => 'Keine Kontrolle im Strafsinn', 'body' => 'Der Besuch dient vor allem der Beratung. Dabei können Belastungen, Hilfsmittel, Pflegekurse und weitere Unterstützungsangebote besprochen werden.']],
        'tip' => 'Termine rechtzeitig vereinbaren und die Bestätigung für die Pflegekasse aufbewahren.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Häusliche Pflege und Beratungsbesuche', 'url' => $bmgHomeCare]],
        'related' => ['pflegegeld', 'pflegeberatung', 'pflegekurse'], 'checked_at' => $checkedAt,
    ],
    'betreutes-wohnen' => [
        'title' => 'Betreutes Wohnen', 'letter' => 'B',
        'summary' => 'Wohnform mit eigenem Wohnraum und vertraglich vereinbarten Unterstützungsangeboten.',
        'intro' => 'Betreutes Wohnen verbindet eine eigene Wohnung mit Service- oder Betreuungsleistungen. Der Begriff allein sagt nicht aus, wie viel Pflege verfügbar ist oder ob nachts Personal anwesend ist.',
        'sections' => [['title' => 'Verträge genau lesen', 'body' => 'Miete, Grundservice, Wahlleistungen und Pflege können in unterschiedlichen Verträgen geregelt sein. Nicht jedes Angebot fällt vollständig unter das Wohn- und Betreuungsvertragsgesetz.']],
        'tip' => 'Vor Vertragsabschluss nach Nachtbereitschaft, Notruf, frei wählbarem Pflegedienst und allen monatlichen Kosten fragen.',
        'sources' => [['label' => 'Wohn- und Betreuungsvertragsgesetz', 'url' => 'https://www.gesetze-im-internet.de/wbvg/BJNR231910009.html']],
        'related' => ['pflege-wohngemeinschaft', 'hausnotruf', 'barrierefreiheit'], 'checked_at' => $checkedAt,
    ],
    'demenz' => [
        'title' => 'Demenz', 'letter' => 'D',
        'summary' => 'Oberbegriff für Erkrankungen, die Gedächtnis, Denken und Alltagsfähigkeiten beeinträchtigen.',
        'intro' => 'Eine Demenz kann sich unter anderem durch Vergesslichkeit, Orientierungsprobleme, Sprachveränderungen oder Schwierigkeiten bei vertrauten Aufgaben zeigen. Eine ärztliche Abklärung ist wichtig, weil verschiedene Ursachen möglich sind.',
        'sections' => [['title' => 'Unterstützung im Alltag', 'body' => 'Eine klare Tagesstruktur, vertraute Abläufe und angemessene Beschäftigung können Sicherheit geben. Angehörige sollten frühzeitig Beratung und Entlastung nutzen.']],
        'tip' => 'Bei neuen oder rasch zunehmenden Veränderungen zuerst ärztlichen Rat suchen und nicht selbst diagnostizieren.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Mit einer Demenz leben', 'url' => 'https://www.bundesgesundheitsministerium.de/themen/pflege/online-ratgeber-demenz/mit-einer-demenz-leben']],
        'related' => ['alltagsbegleitung', 'tagespflege', 'pflegegrad'], 'checked_at' => $checkedAt,
    ],
    'digitale-pflegeanwendung' => [
        'title' => 'Digitale Pflegeanwendung (DiPA)', 'letter' => 'D',
        'summary' => 'Geprüfte digitale Anwendung zur Unterstützung des Pflegealltags.',
        'intro' => 'Digitale Pflegeanwendungen können beispielsweise Mobilität, Orientierung, Kommunikation oder die Organisation der Pflege unterstützen. Dazu zählen Apps, Webanwendungen und andere Software.',
        'sections' => [['title' => 'Nicht jede Pflege-App ist eine DiPA', 'body' => 'Für eine Leistung der Pflegeversicherung gelten besondere Anforderungen und ein geregeltes Verfahren. Zusätzlich können ergänzende Unterstützungsleistungen notwendig sein.']],
        'tip' => 'Vor dem Kauf prüfen, ob die Anwendung im offiziellen Verzeichnis steht und wie der Antrag bei der Pflegekasse erfolgt.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Digitale Pflegeanwendungen', 'url' => 'https://www.bundesgesundheitsministerium.de/themen/pflege/online-ratgeber-pflege/leistungen-der-pflegeversicherung/leistungen-im-ueberblick/digitale-pflegeanwendungen']],
        'related' => ['pflegehilfsmittel', 'pflegekasse', 'pflegeberatung'], 'checked_at' => $checkedAt,
    ],
    'eigenanteil' => [
        'title' => 'Eigenanteil', 'letter' => 'E',
        'summary' => 'Kostenanteil, den die pflegebedürftige Person selbst tragen muss.',
        'intro' => 'Die Pflegeversicherung ist eine Teilkostenversicherung. Deshalb können trotz Versicherungsleistungen eigene Kosten entstehen, sowohl bei ambulanter als auch bei stationärer Versorgung.',
        'sections' => [['title' => 'Kosten unterscheiden', 'body' => 'Im Pflegeheim gehören unter anderem pflegebedingter Eigenanteil, Unterkunft, Verpflegung und Investitionskosten zur Rechnung. Bei ambulanten Diensten können private Zusatzleistungen oder Beträge oberhalb des Budgets entstehen.']],
        'tip' => 'Immer einen persönlichen Gesamtkostenplan verlangen und nicht nur einzelne Leistungsbeträge vergleichen.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Vollstationäre Pflege und Kosten', 'url' => $bmgHome]],
        'related' => ['einrichtungseinheitlicher-eigenanteil', 'investitionskosten', 'hilfe-zur-pflege'], 'checked_at' => $checkedAt,
    ],
    'einrichtungseinheitlicher-eigenanteil' => [
        'title' => 'Einrichtungseinheitlicher Eigenanteil (EEE)', 'letter' => 'E',
        'summary' => 'Pflegebedingter Eigenanteil, der innerhalb eines Pflegeheims grundsätzlich einheitlich berechnet wird.',
        'intro' => 'Der einrichtungseinheitliche Eigenanteil betrifft die nicht durch die Pflegeversicherung gedeckten pflegebedingten Kosten eines Heims. Er ist nicht mit der gesamten monatlichen Heimrechnung gleichzusetzen.',
        'sections' => [['title' => 'Weitere Kosten kommen hinzu', 'body' => 'Unterkunft, Verpflegung, Investitionskosten und freiwillige Zusatzleistungen werden gesondert berechnet. Leistungszuschläge der Pflegeversicherung können den pflegebedingten Eigenanteil abhängig von der Aufenthaltsdauer reduzieren.']],
        'tip' => 'Beim Heim immer nach EEE, Leistungszuschlag und vollständigem monatlichem Gesamtbetrag fragen.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Vollstationäre Pflege im Heim', 'url' => $bmgHome]],
        'related' => ['eigenanteil', 'investitionskosten', 'stationaere-pflege'], 'checked_at' => $checkedAt,
    ],
    'entlassmanagement' => [
        'title' => 'Entlassmanagement', 'letter' => 'E',
        'summary' => 'Organisation der Anschlussversorgung nach einem Krankenhausaufenthalt.',
        'intro' => 'Das Entlassmanagement soll verhindern, dass nach der Krankenhausentlassung Versorgungslücken entstehen. Dazu wird der Bedarf an Medikamenten, Hilfsmitteln, Pflege, Rehabilitation oder weiteren Behandlungen geprüft.',
        'sections' => [['title' => 'Frühzeitig beginnen', 'body' => 'Bei komplexem Unterstützungsbedarf soll das Krankenhaus rechtzeitig einen Entlassplan erstellen und mit Zustimmung der betroffenen Person notwendige Leistungserbringer und Kostenträger einbeziehen.']],
        'tip' => 'Noch während des Aufenthalts nach Entlassdatum, Verordnungen, Pflegebedarf und verantwortlicher Kontaktperson fragen.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Entlassmanagement', 'url' => 'https://www.bundesgesundheitsministerium.de/service/begriffe-von-a-z/e/entlassmanagement']],
        'related' => ['uebergangspflege', 'kurzzeitpflege', 'ambulante-pflege'], 'checked_at' => $checkedAt,
    ],
    'ersatzpflege' => [
        'title' => 'Ersatzpflege', 'letter' => 'E',
        'summary' => 'Vorübergehende Übernahme der Pflege durch eine andere Person oder einen Dienst.',
        'intro' => 'Ersatzpflege wird benötigt, wenn die sonst pflegende Person zeitweise ausfällt. Im Leistungsrecht wird dafür häufig der Begriff Verhinderungspflege verwendet.',
        'sections' => [['title' => 'Unterschiedliche Formen', 'body' => 'Die Vertretung kann stundenweise oder für mehrere Tage erfolgen und beispielsweise durch einen Pflegedienst, Bekannte oder Angehörige übernommen werden. Die Erstattung richtet sich nach der konkreten Konstellation.']],
        'tip' => 'Vorab mit der Pflegekasse klären, welche Nachweise und Rechnungen erforderlich sind.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Verhinderungspflege', 'url' => 'https://www.bundesgesundheitsministerium.de/verhinderungspflege/seite']],
        'related' => ['verhinderungspflege', 'pflegeperson', 'kurzzeitpflege'], 'checked_at' => $checkedAt,
    ],
    'familienpflegezeit' => [
        'title' => 'Familienpflegezeit', 'letter' => 'F',
        'summary' => 'Zeitlich begrenzte Verringerung der Arbeitszeit zur Pflege naher Angehöriger.',
        'intro' => 'Die Familienpflegezeit kann Beschäftigten ermöglichen, ihre Arbeitszeit für eine längere Pflegephase zu reduzieren. Voraussetzungen, Mindestarbeitszeit und Betriebsgröße sind gesetzlich geregelt.',
        'sections' => [['title' => 'Nicht mit Pflegezeit verwechseln', 'body' => 'Pflegezeit und Familienpflegezeit haben unterschiedliche Höchstdauern und Voraussetzungen. Ankündigungsfristen und Nachweise müssen eingehalten werden.']],
        'tip' => 'Vor einer Vereinbarung arbeitsrechtliche Beratung nutzen und Auswirkungen auf Einkommen und Sozialversicherung prüfen.',
        'sources' => [['label' => 'Familienpflegezeitgesetz', 'url' => 'https://www.gesetze-im-internet.de/fpfzg/']],
        'related' => ['pflegezeit', 'kurzzeitige-arbeitsverhinderung', 'pflegeunterstuetzungsgeld'], 'checked_at' => $checkedAt,
    ],
    'fahrdienst' => [
        'title' => 'Fahrdienst', 'letter' => 'F',
        'summary' => 'Organisierte Beförderung, etwa zur Tagespflege oder zu medizinischen Terminen.',
        'intro' => 'Ein Fahrdienst kann Bestandteil eines Pflegeangebots sein oder separat berechnet werden. Bei der Tagespflege gehört die notwendige Beförderung grundsätzlich zum Leistungsumfang; für Krankenfahrten gelten andere Regeln.',
        'sections' => [['title' => 'Vorher genau klären', 'body' => 'Wichtig sind Abholgebiet, Begleitung, Rollstuhltransport, Wartezeiten und Kosten. Ein Einrichtungsfahrdienst ist nicht automatisch ein medizinischer Krankentransport.']],
        'tip' => 'Schriftlich bestätigen lassen, ob Hin- und Rückfahrt im Preis enthalten sind.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Teilstationäre Tages- oder Nachtpflege', 'url' => 'https://www.bundesgesundheitsministerium.de/themen/pflege/online-ratgeber-pflege/leistungen-der-pflegeversicherung/teilstationaere-pflege']],
        'related' => ['tagespflege', 'barrierefreiheit', 'pflegevertrag'], 'checked_at' => $checkedAt,
    ],
    'grundpflege' => [
        'title' => 'Grundpflege', 'letter' => 'G',
        'summary' => 'Älterer Sammelbegriff für grundlegende Unterstützung im täglichen Leben.',
        'intro' => 'Mit Grundpflege werden häufig Hilfen bei Körperpflege, Ernährung und Mobilität bezeichnet. Im Recht der Pflegeversicherung wird heute genauer von körperbezogenen Pflegemaßnahmen gesprochen.',
        'sections' => [['title' => 'Abgrenzung zur Behandlungspflege', 'body' => 'Grundlegende Alltagshilfe ist nicht dasselbe wie ärztlich verordnete medizinische Behandlungspflege, etwa Medikamentengabe oder Verbandswechsel. Beide Leistungsarten können durch denselben Pflegedienst erbracht werden, werden aber unterschiedlich finanziert.']],
        'tip' => 'Im Angebot genau prüfen, welche einzelne Hilfe hinter dem Sammelbegriff steht.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Häusliche Krankenpflege', 'url' => 'https://www.bundesgesundheitsministerium.de/haushaltshilfe/']],
        'related' => ['behandlungspflege', 'ambulante-pflege', 'pflegesachleistung'], 'checked_at' => $checkedAt,
    ],
    'hausnotruf' => [
        'title' => 'Hausnotruf', 'letter' => 'H',
        'summary' => 'Notrufsystem, mit dem zu Hause schnell Hilfe angefordert werden kann.',
        'intro' => 'Ein Hausnotruf besteht meist aus einem Notrufknopf und einer erreichbaren Zentrale. Je nach Vertrag wird eine Kontaktperson, ein Bereitschaftsdienst oder im Notfall der Rettungsdienst verständigt.',
        'sections' => [['title' => 'Leistungsumfang vergleichen', 'body' => 'Gerät, Installation, Schlüsselhinterlegung, Einsatzdienst und Zusatzfunktionen können unterschiedlich berechnet werden. Unter Voraussetzungen kann die Pflegekasse einen Zuschuss als Pflegehilfsmittel gewähren.']],
        'tip' => 'Vor Vertragsabschluss testen, ob der Notruf aus allen wichtigen Bereichen der Wohnung funktioniert.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Pflegehilfsmittel', 'url' => 'https://www.bundesgesundheitsministerium.de/pflege-zu-hause/pflegehilfsmittel']],
        'related' => ['pflegehilfsmittel', 'betreutes-wohnen', 'wohnraumanpassung'], 'checked_at' => $checkedAt,
    ],
    'hilfe-zur-pflege' => [
        'title' => 'Hilfe zur Pflege', 'letter' => 'H',
        'summary' => 'Sozialhilfeleistung, wenn notwendige Pflegekosten nicht aus eigenen Mitteln gedeckt werden können.',
        'intro' => 'Reichen Leistungen der Pflegeversicherung, Einkommen und Vermögen für notwendige Pflege nicht aus, kann unter gesetzlichen Voraussetzungen Hilfe zur Pflege beim Sozialhilfeträger beantragt werden.',
        'sections' => [['title' => 'Einzelfallprüfung', 'body' => 'Bedarf, Einkommen, Vermögen und mögliche Ansprüche gegenüber anderen Trägern werden geprüft. Die Leistung beginnt nicht automatisch mit einem Pflegegrad.']],
        'tip' => 'Den Sozialhilfeträger möglichst vor Entstehung größerer ungedeckter Kosten kontaktieren und Unterlagen vollständig einreichen.',
        'sources' => [['label' => 'Sozialgesetzbuch XII: Hilfe zur Pflege', 'url' => 'https://www.gesetze-im-internet.de/sgb_12/__61.html']],
        'related' => ['eigenanteil', 'stationaere-pflege', 'pflegeberatung'], 'checked_at' => $checkedAt,
    ],
    'hilfsmittel' => [
        'title' => 'Hilfsmittel', 'letter' => 'H',
        'summary' => 'Produkte, die eine medizinische Behandlung sichern, Behinderungen ausgleichen oder den Alltag erleichtern.',
        'intro' => 'Zu Hilfsmitteln der Krankenversicherung können beispielsweise Rollstühle, Hörhilfen oder Gehhilfen gehören. Pflegehilfsmittel verfolgen speziell das Ziel, Pflege zu erleichtern oder Selbstständigkeit zu fördern.',
        'sections' => [['title' => 'Zuständigkeit unterscheiden', 'body' => 'Je nach Zweck kann die Kranken- oder Pflegekasse zuständig sein. Eine ärztliche Verordnung ist bei Hilfsmitteln der Krankenversicherung häufig wichtig, ersetzt aber nicht immer die Genehmigung.']],
        'tip' => 'Vor dem Kauf Kostenträger, Vertragspartner, Zuzahlung und mögliche Leihstellung klären.',
        'sources' => [['label' => 'Sozialgesetzbuch V: Hilfsmittel', 'url' => 'https://www.gesetze-im-internet.de/sgb_5/__33.html']],
        'related' => ['pflegehilfsmittel', 'wohnraumanpassung', 'barrierefreiheit'], 'checked_at' => $checkedAt,
    ],
    'hospiz' => [
        'title' => 'Hospiz', 'letter' => 'H',
        'summary' => 'Angebot zur Begleitung schwerstkranker und sterbender Menschen sowie ihrer Angehörigen.',
        'intro' => 'Hospizarbeit stellt Lebensqualität, Selbstbestimmung und Begleitung in der letzten Lebensphase in den Mittelpunkt. Sie kann ambulant zu Hause oder stationär in einem Hospiz stattfinden.',
        'sections' => [['title' => 'Hospiz und Palliativversorgung', 'body' => 'Hospizliche Begleitung und palliative medizinisch-pflegerische Versorgung ergänzen sich, sind aber nicht identisch. Die passende Versorgung richtet sich nach Bedarf und Wunsch der betroffenen Person.']],
        'tip' => 'Frühzeitig eine Hospiz- oder Palliativberatungsstelle kontaktieren; Beratung ist auch für Angehörige möglich.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Versorgung für Schwerstkranke und Sterbende', 'url' => 'https://www.bundesgesundheitsministerium.de/themen/pflege/online-ratgeber-pflege/leistungen-der-pflegeversicherung/schwerstkranke-und-sterbende/seite']],
        'related' => ['palliativpflege', 'sapv', 'vorsorgevollmacht'], 'checked_at' => $checkedAt,
    ],
    'investitionskosten' => [
        'title' => 'Investitionskosten', 'letter' => 'I',
        'summary' => 'Gesondert berechnete Kosten einer Pflegeeinrichtung für Gebäude und betriebsnotwendige Ausstattung.',
        'intro' => 'Pflegeeinrichtungen können unter gesetzlichen und landesrechtlichen Voraussetzungen Investitionsaufwendungen auf Bewohnerinnen und Bewohner umlegen. Diese Kosten sind nicht Teil des pflegebedingten Eigenanteils.',
        'sections' => [['title' => 'Höhe ist einrichtungsabhängig', 'body' => 'Gebäude, Finanzierung und öffentliche Förderung unterscheiden sich. Deshalb können Investitionskosten zwischen Einrichtungen deutlich variieren.']],
        'tip' => 'Den aktuellen Tages- oder Monatsbetrag und mögliche angekündigte Änderungen vor Vertragsschluss schriftlich erfragen.',
        'sources' => [['label' => 'Sozialgesetzbuch XI: Finanzierung der Pflegeeinrichtungen', 'url' => 'https://www.gesetze-im-internet.de/sgb_11/__82.html']],
        'related' => ['eigenanteil', 'einrichtungseinheitlicher-eigenanteil', 'pflegevertrag'], 'checked_at' => $checkedAt,
    ],
    'kombinationsleistung' => [
        'title' => 'Kombinationsleistung', 'letter' => 'K',
        'summary' => 'Verbindung von ambulanten Pflegesachleistungen mit anteiligem Pflegegeld.',
        'intro' => 'Wer einen Pflegedienst nutzt, das Sachleistungsbudget aber nicht vollständig ausschöpft, kann unter Voraussetzungen zusätzlich anteiliges Pflegegeld erhalten.',
        'sections' => [['title' => 'Anteilige Berechnung', 'body' => 'Das Pflegegeld vermindert sich im Verhältnis zu den genutzten Sachleistungen. Auch ein Umwandlungsanspruch kann die Berechnung beeinflussen.']],
        'tip' => 'Monatliche Abrechnung prüfen und sich von der Pflegekasse eine Beispielberechnung geben lassen.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Häusliche Pflege', 'url' => $bmgHomeCare]],
        'related' => ['pflegegeld', 'pflegesachleistung', 'umwandlungsanspruch'], 'checked_at' => $checkedAt,
    ],
    'krankenkasse-und-pflegekasse' => [
        'title' => 'Krankenkasse und Pflegekasse', 'letter' => 'K',
        'summary' => 'Zwei unterschiedliche Kostenträger mit verschiedenen Aufgaben.',
        'intro' => 'Die Krankenkasse finanziert vor allem medizinische Leistungen. Die Pflegekasse ist für Leistungen der Pflegeversicherung zuständig und organisatorisch bei der Krankenkasse angesiedelt.',
        'sections' => [['title' => 'Beispiel', 'body' => 'Ärztlich verordnete Behandlungspflege kann Aufgabe der Krankenkasse sein, während körperbezogene Pflege über Pflegesachleistungen der Pflegekasse finanziert wird. Zuständigkeiten können sich im Einzelfall überschneiden.']],
        'tip' => 'Bei Ablehnung nicht nur den Anbieter fragen, sondern einen schriftlichen Bescheid des zuständigen Kostenträgers verlangen.',
        'sources' => [['label' => 'Sozialgesetzbuch XI: Soziale Pflegeversicherung', 'url' => 'https://www.gesetze-im-internet.de/sgb_11/BJNR101500994.html']],
        'related' => ['pflegekasse', 'sgb-v', 'sgb-xi'], 'checked_at' => $checkedAt,
    ],
    'kurzzeitige-arbeitsverhinderung' => [
        'title' => 'Kurzzeitige Arbeitsverhinderung', 'letter' => 'K',
        'summary' => 'Kurzfristige Freistellung von der Arbeit in einer akuten Pflegesituation.',
        'intro' => 'Beschäftigte können unter gesetzlichen Voraussetzungen für eine begrenzte Zahl von Arbeitstagen der Arbeit fernbleiben, um eine akut notwendige Pflege zu organisieren oder sicherzustellen.',
        'sections' => [['title' => 'Arbeitgeber informieren', 'body' => 'Die Verhinderung und voraussichtliche Dauer müssen unverzüglich mitgeteilt werden. Ein ärztlicher Nachweis kann verlangt werden. Für den Einkommensausfall kann Pflegeunterstützungsgeld infrage kommen.']],
        'tip' => 'Arbeitgeber und Pflegekasse sofort kontaktieren und alle Nachweise aufbewahren.',
        'sources' => [['label' => 'Pflegezeitgesetz', 'url' => 'https://www.gesetze-im-internet.de/pflegezg/']],
        'related' => ['pflegeunterstuetzungsgeld', 'pflegezeit', 'familienpflegezeit'], 'checked_at' => $checkedAt,
    ],
    'medizinischer-dienst' => [
        'title' => 'Medizinischer Dienst (MD)', 'letter' => 'M',
        'summary' => 'Unabhängiger medizinischer und pflegefachlicher Beratungs- und Begutachtungsdienst.',
        'intro' => 'Der Medizinische Dienst unterstützt die gesetzliche Kranken- und Pflegeversicherung, unter anderem bei Pflegebegutachtungen und Qualitätsprüfungen von Pflegeeinrichtungen.',
        'sections' => [['title' => 'Nicht die Pflegekasse selbst', 'body' => 'Der MD erstellt eine fachliche Einschätzung. Den rechtsverbindlichen Bescheid über einen Pflegegrad erlässt die Pflegekasse.']],
        'tip' => 'Das Gutachten zusammen mit dem Bescheid prüfen und bei Unklarheiten Pflegeberatung nutzen.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Begutachtung', 'url' => 'https://www.bundesgesundheitsministerium.de/service/begriffe-von-a-z/b/begutachtung-pflegeversicherung']],
        'related' => ['begutachtung', 'pflegegrad', 'qualitaetspruefung'], 'checked_at' => $checkedAt,
    ],
    'nachtpflege' => [
        'title' => 'Nachtpflege', 'letter' => 'N',
        'summary' => 'Teilstationäre Betreuung und Pflege während der Nacht.',
        'intro' => 'Bei der Nachtpflege wird eine pflegebedürftige Person nachts in einer Einrichtung versorgt und lebt ansonsten weiterhin zu Hause. Das Angebot kann Angehörige bei hohem nächtlichem Betreuungsbedarf entlasten.',
        'sections' => [['title' => 'Seltenes Angebot', 'body' => 'Nachtpflege ist regional deutlich seltener verfügbar als Tagespflege. Leistungen, Beförderung, Betreuungszeiten und Kosten müssen direkt mit der Einrichtung geklärt werden.']],
        'tip' => 'Nach Probenacht, Aufnahmebedingungen und Organisation der Hin- und Rückfahrt fragen.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Teilstationäre Tages- oder Nachtpflege', 'url' => 'https://www.bundesgesundheitsministerium.de/themen/pflege/online-ratgeber-pflege/leistungen-der-pflegeversicherung/teilstationaere-pflege']],
        'related' => ['tagespflege', 'angehoerigenpflege', 'fahrdienst'], 'checked_at' => $checkedAt,
    ],
    'palliativpflege' => [
        'title' => 'Palliativpflege', 'letter' => 'P',
        'summary' => 'Pflege zur Linderung von Beschwerden und Erhaltung von Lebensqualität bei schwerer Erkrankung.',
        'intro' => 'Palliativpflege richtet sich an Menschen mit einer fortschreitenden, nicht heilbaren Erkrankung. Im Mittelpunkt stehen Symptomlinderung, persönliche Wünsche und Unterstützung der Angehörigen.',
        'sections' => [['title' => 'An vielen Orten möglich', 'body' => 'Palliative Versorgung kann zu Hause, im Pflegeheim, im Hospiz oder im Krankenhaus erfolgen. Bei besonders komplexem Bedarf kann SAPV verordnet werden.']],
        'tip' => 'Behandelnde Ärztinnen und Ärzte frühzeitig nach einem Palliativ- und Notfallplan fragen.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Angebote für Sterbenskranke', 'url' => 'https://www.bundesgesundheitsministerium.de/themen/krankenversicherung/online-ratgeber-krankenversicherung/medizinische-versorgung-und-leistungen-der-krankenversicherung/angebote-fuer-sterbenskranke']],
        'related' => ['sapv', 'hospiz', 'behandlungspflege'], 'checked_at' => $checkedAt,
    ],
    'pflegebeduerftigkeit' => [
        'title' => 'Pflegebedürftigkeit', 'letter' => 'P',
        'summary' => 'Dauerhafter Hilfebedarf wegen gesundheitlich bedingter Beeinträchtigungen der Selbstständigkeit.',
        'intro' => 'Pflegebedürftigkeit im Sinne der Pflegeversicherung liegt vor, wenn ein Mensch körperliche, kognitive oder psychische Beeinträchtigungen nicht selbstständig bewältigen kann und deshalb Hilfe benötigt.',
        'sections' => [['title' => 'Gesetzliche Voraussetzungen', 'body' => 'Der Unterstützungsbedarf muss voraussichtlich mindestens sechs Monate bestehen und eine gesetzlich festgelegte Schwere erreichen. Die Feststellung erfolgt durch eine Begutachtung.']],
        'tip' => 'Nicht nur körperliche Hilfe dokumentieren, sondern auch Erinnerung, Anleitung, Beaufsichtigung und psychische Belastungen.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Pflegebedürftigkeit', 'url' => $bmgNeed]],
        'related' => ['pflegegrad', 'begutachtung', 'antrag-pflegegrad'], 'checked_at' => $checkedAt,
    ],
    'pflegeheim' => [
        'title' => 'Pflegeheim', 'letter' => 'P',
        'summary' => 'Vollstationäre Einrichtung für dauerhafte Pflege, Betreuung, Unterkunft und Verpflegung.',
        'intro' => 'In einem Pflegeheim leben Menschen, die regelmäßig umfassende Unterstützung benötigen. Pflege und Betreuung werden rund um die Uhr organisatorisch sichergestellt.',
        'sections' => [['title' => 'Nicht jedes Seniorenwohnen ist ein Pflegeheim', 'body' => 'Betreutes Wohnen, Seniorenresidenzen und Pflege-Wohngemeinschaften können andere rechtliche und personelle Strukturen haben. Entscheidend sind Zulassung, Vertrag und tatsächlicher Leistungsumfang.']],
        'tip' => 'Vor Einzug Zimmer, Pflegekonzept, Personalerreichbarkeit, Kosten und aktuellen Qualitätsbericht prüfen.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Pflegeeinrichtungen (stationär)', 'url' => 'https://www.bundesgesundheitsministerium.de/service/begriffe-von-a-z/p/pflegeheim']],
        'related' => ['stationaere-pflege', 'pflegevertrag', 'qualitaetspruefung'], 'checked_at' => $checkedAt,
    ],
    'pflegekasse' => [
        'title' => 'Pflegekasse', 'letter' => 'P',
        'summary' => 'Träger der sozialen Pflegeversicherung und zentrale Anlaufstelle für Pflegeleistungen.',
        'intro' => 'Die Pflegekasse ist bei der jeweiligen gesetzlichen Krankenkasse eingerichtet. Sie bearbeitet Anträge, beauftragt Begutachtungen, bewilligt Leistungen und bietet Pflegeberatung an.',
        'sections' => [['title' => 'Private Pflegeversicherung', 'body' => 'Privat Krankenversicherte haben eine private Pflege-Pflichtversicherung. Zuständigkeiten und Verfahren sind vergleichbar, Ansprechpartner und Abrechnung können sich aber unterscheiden.']],
        'tip' => 'Bei wichtigen Entscheidungen immer einen schriftlichen Bescheid verlangen.',
        'sources' => [['label' => 'Sozialgesetzbuch XI: Soziale Pflegeversicherung', 'url' => 'https://www.gesetze-im-internet.de/sgb_11/BJNR101500994.html']],
        'related' => ['krankenkasse-und-pflegekasse', 'pflegeberatung', 'antrag-pflegegrad'], 'checked_at' => $checkedAt,
    ],
    'pflegekurse' => [
        'title' => 'Pflegekurse', 'letter' => 'P',
        'summary' => 'Kostenfreie Schulungen für Angehörige und ehrenamtlich Pflegende.',
        'intro' => 'Pflegekurse vermitteln praktische Fähigkeiten und Wissen für die häusliche Pflege. Themen können rückenschonendes Bewegen, Körperpflege, Demenz, Hilfsmittel und Selbstfürsorge sein.',
        'sections' => [['title' => 'Auch zu Hause möglich', 'body' => 'Pflegekassen bieten Kurse selbst oder gemeinsam mit geeigneten Partnern an. Auf Wunsch kann eine individuelle Schulung in der häuslichen Umgebung infrage kommen.']],
        'tip' => 'Bei der Pflegekasse gezielt nach einem Kurs passend zur konkreten Pflegesituation fragen.',
        'sources' => [['label' => 'Sozialgesetzbuch XI: Pflegekurse', 'url' => 'https://www.gesetze-im-internet.de/sgb_11/__45.html']],
        'related' => ['angehoerigenpflege', 'beratungsbesuch', 'pflegeperson'], 'checked_at' => $checkedAt,
    ],
    'pflegeperson' => [
        'title' => 'Pflegeperson', 'letter' => 'P',
        'summary' => 'Person, die einen pflegebedürftigen Menschen nicht erwerbsmäßig zu Hause pflegt.',
        'intro' => 'Pflegepersonen sind häufig Angehörige, können aber auch Freunde, Nachbarn oder andere nahestehende Menschen sein. Unter Voraussetzungen bestehen Ansprüche zur sozialen Absicherung.',
        'sections' => [['title' => 'Nicht dasselbe wie Pflegefachkraft', 'body' => 'Eine Pflegeperson im Sinne der Pflegeversicherung handelt nicht erwerbsmäßig. Eine Pflegefachkraft hat dagegen eine staatlich geregelte berufliche Qualifikation.']],
        'tip' => 'Pflegeumfang und Erwerbstätigkeit der Pflegekasse korrekt mitteilen, damit mögliche Sozialversicherungsleistungen geprüft werden.',
        'sources' => [['label' => 'Sozialgesetzbuch XI: Begriff der Pflegeperson', 'url' => 'https://www.gesetze-im-internet.de/sgb_11/__19.html']],
        'related' => ['angehoerigenpflege', 'pflegegeld', 'verhinderungspflege'], 'checked_at' => $checkedAt,
    ],
    'pflegeplan' => [
        'title' => 'Pflegeplan und Versorgungsplan', 'letter' => 'P',
        'summary' => 'Schriftliche Übersicht über Bedarf, Ziele, Aufgaben und vereinbarte Unterstützung.',
        'intro' => 'Ein Pflegeplan beschreibt, welche Hilfe wann, wie und durch wen erbracht wird. In der Pflegeberatung kann zusätzlich ein Versorgungsplan erstellt werden, der Leistungen und Zuständigkeiten zusammenführt.',
        'sections' => [['title' => 'Regelmäßig anpassen', 'body' => 'Gesundheitszustand, Fähigkeiten und familiäre Möglichkeiten können sich verändern. Deshalb sollte die Planung überprüft und bei Bedarf aktualisiert werden.']],
        'tip' => 'Ansprechpartner, Notfallnummern, Medikamente und Vertretungsregeln in die praktische Planung aufnehmen.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Versorgungsplan', 'url' => $bmgSupport]],
        'related' => ['pflegeberatung', 'pflegevertrag', 'entlassmanagement'], 'checked_at' => $checkedAt,
    ],
    'pflegestuetzpunkt' => [
        'title' => 'Pflegestützpunkt', 'letter' => 'P',
        'summary' => 'Regionale, trägerübergreifende Beratungsstelle für Fragen rund um Pflege und Unterstützung.',
        'intro' => 'Pflegestützpunkte beraten Pflegebedürftige und Angehörige zu Leistungen, Anträgen, Versorgungsangeboten und regionalen Hilfen. Die Beratung soll unabhängig und wohnortnah erfolgen.',
        'sections' => [['title' => 'Mehr als eine Adressauskunft', 'body' => 'Bei komplexem Bedarf kann die Beratungsstelle helfen, verschiedene Leistungen und Anbieter zu koordinieren. Zuständigkeit und Öffnungszeiten sind regional unterschiedlich.']],
        'tip' => 'Zum Termin Bescheide, Vollmachten, Kostenangebote und eine Fragenliste mitnehmen.',
        'sources' => [['label' => 'Sozialgesetzbuch XI: Pflegestützpunkte', 'url' => 'https://www.gesetze-im-internet.de/sgb_11/__7c.html']],
        'related' => ['pflegeberatung', 'pflegekasse', 'pflegeplan'], 'checked_at' => $checkedAt,
    ],
    'pflegeunterstuetzungsgeld' => [
        'title' => 'Pflegeunterstützungsgeld', 'letter' => 'P',
        'summary' => 'Lohnersatzleistung für eine kurzzeitige Arbeitsverhinderung in einer akuten Pflegesituation.',
        'intro' => 'Pflegeunterstützungsgeld kann unter Voraussetzungen den Einkommensausfall ausgleichen, wenn Beschäftigte kurzfristig nicht arbeiten, um die Pflege eines nahen Angehörigen zu organisieren oder sicherzustellen.',
        'sections' => [['title' => 'Antrag erforderlich', 'body' => 'Die Leistung wird nicht automatisch vom Arbeitgeber gezahlt. Zuständig ist regelmäßig die Pflegekasse oder das private Pflegeversicherungsunternehmen der pflegebedürftigen Person.']],
        'tip' => 'Antrag und ärztlichen Nachweis möglichst sofort einreichen.',
        'sources' => [['label' => 'Pflegezeitgesetz', 'url' => 'https://www.gesetze-im-internet.de/pflegezg/']],
        'related' => ['kurzzeitige-arbeitsverhinderung', 'pflegezeit', 'familienpflegezeit'], 'checked_at' => $checkedAt,
    ],
    'pflegevertrag' => [
        'title' => 'Pflegevertrag', 'letter' => 'P',
        'summary' => 'Vertrag über Art, Umfang, Kosten und Bedingungen professioneller Pflegeleistungen.',
        'intro' => 'Ein ambulanter Pflegevertrag sollte die vereinbarten Leistungen und Vergütungen verständlich aufführen. Bei stationärem Wohnen mit Pflege gelten zusätzlich besondere Verbraucherschutzregeln.',
        'sections' => [['title' => 'Vor Unterschrift prüfen', 'body' => 'Wichtig sind Leistungsumfang, private Kosten, Abrechnung, Änderungen, Haftung, Schlüsselregelung und Kündigung. Mündliche Zusagen sollten schriftlich aufgenommen werden.']],
        'tip' => 'Vertrag und Anlagen in Ruhe lesen und eine Kopie aller unterschriebenen Unterlagen behalten.',
        'sources' => [['label' => 'Sozialgesetzbuch XI: Pflegevertrag bei häuslicher Pflege', 'url' => 'https://www.gesetze-im-internet.de/sgb_11/__120.html']],
        'related' => ['ambulante-pflege', 'pflegeheim', 'eigenanteil'], 'checked_at' => $checkedAt,
    ],
    'pflege-wohngemeinschaft' => [
        'title' => 'Pflege-Wohngemeinschaft', 'letter' => 'P',
        'summary' => 'Gemeinsame Wohnform, in der Pflege und Unterstützung ambulant organisiert werden.',
        'intro' => 'In einer Pflege-WG leben mehrere Menschen in einer gemeinsamen Wohnung und organisieren Unterstützung gemeinschaftlich. Mietvertrag, Pflegevertrag und Organisation können rechtlich voneinander getrennt sein.',
        'sections' => [['title' => 'Selbstbestimmung prüfen', 'body' => 'Entscheidend ist, wer Personal, Alltag und Anbieter auswählt. Manche gemeinschaftlichen Wohnformen ähneln in ihrem Leistungsumfang stärker einer stationären Einrichtung und unterliegen anderen Regeln.']],
        'tip' => 'Nach Mitbestimmung, Nachtversorgung, Präsenzkraft, Vertretung und allen getrennten Verträgen fragen.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Pflege-Wohngemeinschaften', 'url' => $bmgWg]],
        'related' => ['wohngruppenzuschlag', 'betreutes-wohnen', 'ambulante-pflege'], 'checked_at' => $checkedAt,
    ],
    'pflegezeit' => [
        'title' => 'Pflegezeit', 'letter' => 'P',
        'summary' => 'Zeitlich begrenzte vollständige oder teilweise Freistellung zur Pflege naher Angehöriger.',
        'intro' => 'Beschäftigte können unter gesetzlichen Voraussetzungen Pflegezeit beanspruchen, um einen nahen Angehörigen in häuslicher Umgebung zu pflegen. Für die Begleitung in der letzten Lebensphase gelten besondere Regeln.',
        'sections' => [['title' => 'Betriebsgröße und Fristen beachten', 'body' => 'Der Anspruch hängt unter anderem von der Zahl der Beschäftigten ab. Die Pflegezeit muss rechtzeitig angekündigt und der Pflegebedarf nachgewiesen werden.']],
        'tip' => 'Vor der Ankündigung Dauer, Finanzierung und Sozialversicherung beraten lassen.',
        'sources' => [['label' => 'Pflegezeitgesetz', 'url' => 'https://www.gesetze-im-internet.de/pflegezg/']],
        'related' => ['familienpflegezeit', 'kurzzeitige-arbeitsverhinderung', 'pflegeunterstuetzungsgeld'], 'checked_at' => $checkedAt,
    ],
    'qualitaetspruefung' => [
        'title' => 'Qualitätsprüfung', 'letter' => 'Q',
        'summary' => 'Externe Prüfung der Pflegequalität und Abrechnung einer zugelassenen Einrichtung.',
        'intro' => 'Pflegeheime und ambulante Dienste werden regelmäßig durch den Medizinischen Dienst oder den Prüfdienst der privaten Krankenversicherung geprüft. Im Mittelpunkt steht die tatsächliche Versorgung der pflegebedürftigen Menschen.',
        'sections' => [['title' => 'Auch Anlassprüfungen möglich', 'body' => 'Bei konkreten Hinweisen auf Mängel können zusätzliche unangemeldete Prüfungen stattfinden. Ergebnisse werden für Verbraucher veröffentlicht, ersetzen aber keine persönliche Besichtigung.']],
        'tip' => 'Datum und vollständige Ergebnisse der letzten Prüfung ansehen und konkrete Rückfragen an die Einrichtung stellen.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Qualitätsprüfungen', 'url' => $bmgQuality]],
        'related' => ['medizinischer-dienst', 'pflegeheim', 'pflegevertrag'], 'checked_at' => $checkedAt,
    ],
    'sapv' => [
        'title' => 'SAPV', 'letter' => 'S',
        'summary' => 'Spezialisierte ambulante Palliativversorgung für besonders komplexe Situationen.',
        'intro' => 'SAPV bedeutet spezialisierte ambulante Palliativversorgung. Ein multiprofessionelles Team versorgt schwerstkranke Menschen mit besonders aufwendigem palliativmedizinischem und palliativpflegerischem Bedarf.',
        'sections' => [['title' => 'Versorgung zu Hause ermöglichen', 'body' => 'SAPV kann im häuslichen Umfeld, in einer Pflegeeinrichtung oder in anderen geeigneten Wohnformen erbracht werden. Sie wird ärztlich verordnet und von der Krankenkasse geprüft.']],
        'tip' => 'Bei schwer kontrollierbaren Beschwerden behandelnde Ärztinnen, Ärzte oder ein Palliativnetz frühzeitig ansprechen.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Versorgung für Schwerstkranke und Sterbende', 'url' => 'https://www.bundesgesundheitsministerium.de/themen/pflege/online-ratgeber-pflege/leistungen-der-pflegeversicherung/schwerstkranke-und-sterbende/seite']],
        'related' => ['palliativpflege', 'hospiz', 'behandlungspflege'], 'checked_at' => $checkedAt,
    ],
    'sgb-v' => [
        'title' => 'SGB V', 'letter' => 'S',
        'summary' => 'Fünftes Buch Sozialgesetzbuch mit den wichtigsten Regeln der gesetzlichen Krankenversicherung.',
        'intro' => 'Das SGB V regelt unter anderem ärztliche Behandlung, Arznei- und Hilfsmittel, häusliche Krankenpflege, Krankenhausbehandlung und viele Aufgaben der Krankenkassen.',
        'sections' => [['title' => 'Bedeutung für Pflege', 'body' => 'Leistungen wie Behandlungspflege, SAPV oder bestimmte Hilfsmittel können aus der Krankenversicherung kommen, auch wenn sie im Pflegealltag erbracht werden.']],
        'tip' => 'Bei einem Bescheid immer prüfen, ob die Kranken- oder Pflegeversicherung entschieden hat.',
        'sources' => [['label' => 'Sozialgesetzbuch V', 'url' => 'https://www.gesetze-im-internet.de/sgb_5/BJNR024820988.html']],
        'related' => ['sgb-xi', 'krankenkasse-und-pflegekasse', 'behandlungspflege'], 'checked_at' => $checkedAt,
    ],
    'sgb-xi' => [
        'title' => 'SGB XI', 'letter' => 'S',
        'summary' => 'Elftes Buch Sozialgesetzbuch mit den Regeln der sozialen Pflegeversicherung.',
        'intro' => 'Das SGB XI regelt Pflegebedürftigkeit, Pflegegrade, Leistungen der Pflegeversicherung, Beratung, Verträge, Qualität und Aufgaben der Pflegekassen.',
        'sections' => [['title' => 'Teilkostenversicherung', 'body' => 'Die Leistungen decken nicht automatisch alle Pflegekosten. Umfang und Art richten sich nach Pflegegrad, Versorgungsform und weiteren gesetzlichen Voraussetzungen.']],
        'tip' => 'Bei komplizierten Ansprüchen Pflegeberatung nutzen und sich die angewendete Rechtsgrundlage nennen lassen.',
        'sources' => [['label' => 'Sozialgesetzbuch XI', 'url' => 'https://www.gesetze-im-internet.de/sgb_11/BJNR101500994.html']],
        'related' => ['sgb-v', 'pflegekasse', 'pflegegrad'], 'checked_at' => $checkedAt,
    ],
    'uebergangspflege' => [
        'title' => 'Übergangspflege im Krankenhaus', 'letter' => 'U',
        'summary' => 'Kurzfristige Versorgung im Krankenhaus, wenn notwendige Anschlussleistungen nicht rechtzeitig organisiert werden können.',
        'intro' => 'Übergangspflege kann nach einer Krankenhausbehandlung infrage kommen, wenn häusliche Krankenpflege, Kurzzeitpflege, Rehabilitation oder andere notwendige Leistungen nicht oder nur mit erheblichem Aufwand verfügbar sind.',
        'sections' => [['title' => 'Begrenzte Zwischenlösung', 'body' => 'Sie umfasst unter anderem Grund- und Behandlungspflege, Arznei- und Hilfsmittel, Unterkunft, Verpflegung und Entlassmanagement, ist aber zeitlich eng begrenzt.']],
        'tip' => 'Das Entlassmanagement frühzeitig fragen, ob die Voraussetzungen vorliegen und welche Anschlussversorgung geplant ist.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Pflegeleistungen der Krankenkasse', 'url' => 'https://www.bundesgesundheitsministerium.de/themen/pflege/online-ratgeber-pflege/leistungen-der-pflegeversicherung/pflegeleistungen-der-krankenkasse']],
        'related' => ['entlassmanagement', 'kurzzeitpflege', 'behandlungspflege'], 'checked_at' => $checkedAt,
    ],
    'umwandlungsanspruch' => [
        'title' => 'Umwandlungsanspruch', 'letter' => 'U',
        'summary' => 'Möglichkeit, einen Teil nicht genutzter Pflegesachleistungen für anerkannte Alltagsangebote einzusetzen.',
        'intro' => 'Pflegebedürftige können unter Voraussetzungen einen begrenzten Teil ihres ambulanten Sachleistungsbetrags für nach Landesrecht anerkannte Angebote zur Unterstützung im Alltag verwenden.',
        'sections' => [['title' => 'Auswirkung auf Pflegegeld', 'body' => 'Der umgewandelte Betrag wird bei einer Kombinationsleistung wie eine genutzte Pflegesachleistung behandelt und kann deshalb das anteilige Pflegegeld verringern.']],
        'tip' => 'Nur anerkannte Angebote nutzen, Belege sammeln und die Auswirkung auf das Pflegegeld vorher berechnen lassen.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Umwandlungsanspruch', 'url' => $bmgSupport]],
        'related' => ['entlastungsbetrag', 'kombinationsleistung', 'pflegesachleistung'], 'checked_at' => $checkedAt,
    ],
    'vorsorgevollmacht' => [
        'title' => 'Vorsorgevollmacht', 'letter' => 'V',
        'summary' => 'Vollmacht für eine Vertrauensperson, die bei eigener Entscheidungsunfähigkeit handeln soll.',
        'intro' => 'Mit einer Vorsorgevollmacht kann festgelegt werden, wer rechtliche und organisatorische Angelegenheiten übernehmen darf, wenn man selbst dazu nicht mehr in der Lage ist.',
        'sections' => [['title' => 'Umfang bewusst festlegen', 'body' => 'Gesundheit, Pflege, Vermögen, Behörden, Wohnung und Aufenthaltsbestimmung können unterschiedlich geregelt werden. Für manche Geschäfte gelten besondere Formvorschriften.']],
        'tip' => 'Ein offizielles Muster nutzen, die bevollmächtigte Person einbeziehen und bei komplexen Vermögensfragen rechtlichen Rat einholen.',
        'sources' => [['label' => 'Bundesministerium der Justiz: Betreuungsrecht', 'url' => 'https://www.bmj.de/DE/themen/vorsorge_betreuungsrecht/vorsorge_betreuungsrecht_node.html']],
        'related' => ['pflegevertrag', 'pflegeberatung', 'hospiz'], 'checked_at' => $checkedAt,
    ],
    'widerspruch-pflegegrad' => [
        'title' => 'Widerspruch gegen den Pflegegrad', 'letter' => 'W',
        'summary' => 'Rechtsbehelf gegen einen Bescheid der Pflegekasse.',
        'intro' => 'Wer mit der Entscheidung über den Pflegegrad nicht einverstanden ist, kann innerhalb der im Bescheid genannten Frist Widerspruch einlegen. Maßgeblich ist die Rechtsbehelfsbelehrung.',
        'sections' => [['title' => 'Gutachten prüfen', 'body' => 'Die Begründung sollte sich konkret auf übersehene oder falsch bewertete Einschränkungen beziehen. Eine erneute Prüfung oder Begutachtung kann folgen.']],
        'tip' => 'Frist sichern, Gutachten anfordern und die ausführliche Begründung bei Bedarf nachreichen.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Widerspruch gegen Entscheidungen der Pflegekasse', 'url' => 'https://www.bundesgesundheitsministerium.de/service/buergertelefon/beschwerden-ueber-die-kranken-oder-pflegeversicherung']],
        'related' => ['pflegegrad', 'begutachtung', 'pflegeberatung'], 'checked_at' => $checkedAt,
    ],
    'wohnraumanpassung' => [
        'title' => 'Wohnraumanpassung', 'letter' => 'W',
        'summary' => 'Umbauten und technische Veränderungen, die häusliche Pflege oder Selbstständigkeit erleichtern.',
        'intro' => 'Wohnraumanpassung kann beispielsweise den Einbau einer bodengleichen Dusche, Türverbreiterungen, Rampen oder fest installierte technische Hilfen umfassen.',
        'sections' => [['title' => 'Zuschuss vor Baubeginn klären', 'body' => 'Die Pflegekasse kann bei Pflegebedürftigkeit einen Zuschuss zu wohnumfeldverbessernden Maßnahmen gewähren. Zusätzlich können andere Förderprogramme oder Kostenträger infrage kommen.']],
        'tip' => 'Kostenvoranschläge einholen und die schriftliche Entscheidung der Pflegekasse abwarten, bevor der Umbau beginnt.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Zuschüsse zur Wohnungsanpassung', 'url' => 'https://www.bundesgesundheitsministerium.de/pflege-zu-hause/zuschuesse-zur-wohnungsanpassung']],
        'related' => ['barrierefreiheit', 'pflegehilfsmittel', 'hausnotruf'], 'checked_at' => $checkedAt,
    ],
    'wohngruppenzuschlag' => [
        'title' => 'Wohngruppenzuschlag', 'letter' => 'W',
        'summary' => 'Zusätzliche Leistung für bestimmte ambulant betreute Pflege-Wohngemeinschaften.',
        'intro' => 'Der Wohngruppenzuschlag soll gemeinschaftlich organisierte Pflege-WGs bei der Finanzierung einer gemeinsam beauftragten Präsenzkraft unterstützen.',
        'sections' => [['title' => 'Mehrere Voraussetzungen', 'body' => 'Personenzahl, Pflegebedürftigkeit der Mitglieder, gemeinschaftliche Beauftragung und die konkrete Versorgungsstruktur müssen gesetzlichen Anforderungen entsprechen. Nicht jede Senioren-WG erfüllt sie.']],
        'tip' => 'Vor Einzug schriftlich bestätigen lassen, ob die Wohnform die Voraussetzungen erfüllt und wer die Präsenzkraft beauftragt.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Leistungen in Pflege-Wohngruppen', 'url' => $bmgWg]],
        'related' => ['pflege-wohngemeinschaft', 'ambulante-pflege', 'pflegekasse'], 'checked_at' => $checkedAt,
    ],
    'zusaetzliche-betreuungskraft' => [
        'title' => 'Zusätzliche Betreuungskraft', 'letter' => 'Z',
        'summary' => 'Mitarbeitende für zusätzliche Betreuung und Aktivierung in stationären oder teilstationären Einrichtungen.',
        'intro' => 'Zusätzliche Betreuungskräfte begleiten Bewohnerinnen, Bewohner und Tagespflegegäste beispielsweise beim Lesen, Basteln, Spazierengehen oder bei gemeinschaftlichen Aktivitäten.',
        'sections' => [['title' => 'Keine Pflegefachkraft', 'body' => 'Sie ergänzen Pflege und Betreuung, dürfen aber nicht planmäßig für körperbezogene Pflege oder medizinische Behandlungspflege eingesetzt werden.']],
        'tip' => 'Bei einer Besichtigung nach Gruppenangeboten, Einzelbegleitung und tatsächlicher Verfügbarkeit fragen.',
        'sources' => [['label' => 'Bundesgesundheitsministerium: Zusätzliche Betreuungskräfte', 'url' => 'https://www.bundesgesundheitsministerium.de/themen/pflege/pflegekraefte/zusaetzliche-betreuungskraefte/seite']],
        'related' => ['alltagsbegleitung', 'tagespflege', 'pflegeheim'], 'checked_at' => $checkedAt,
    ],
];
