<?php

return [
    'terms' => [
        'ambulante-pflege' => [
            'title' => 'Ambulante Pflege',
            'letter' => 'A',
            'summary' => 'Professionelle Pflege und Unterstützung in der eigenen Wohnung.',
            'intro' => 'Bei der ambulanten Pflege kommen Pflege- oder Betreuungsdienste zu der pflegebedürftigen Person nach Hause. So kann sie trotz Unterstützungsbedarf in ihrer vertrauten Umgebung bleiben.',
            'sections' => [
                ['title' => 'Welche Hilfe ist möglich?', 'body' => 'Je nach persönlichem Bedarf können körperbezogene Pflegemaßnahmen, pflegerische Betreuung und Hilfe im Haushalt vereinbart werden. Medizinische Behandlungspflege wird ärztlich verordnet und über die Krankenversicherung abgerechnet.'],
                ['title' => 'Wer übernimmt die Kosten?', 'body' => 'Bei anerkanntem Pflegegrad kann die Pflegekasse ambulante Pflegesachleistungen übernehmen. Welche Leistungen bezahlt werden und ob ein Eigenanteil entsteht, sollte vor Vertragsabschluss mit dem Pflegedienst und der Pflegekasse geklärt werden.'],
            ],
            'tip' => 'Vor Beginn der Versorgung einen schriftlichen Kostenvoranschlag und einen klaren Leistungsplan anfordern.',
            'sources' => [['label' => 'Bundesgesundheitsministerium: Ambulante Pflegesachleistungen', 'url' => 'https://www.bundesgesundheitsministerium.de/pflege-zu-hause/pflegesachleistungen']],
            'related' => ['pflegesachleistung', 'pflegegeld', 'behandlungspflege'],
            'checked_at' => '2026-07-16',
        ],
        'behandlungspflege' => [
            'title' => 'Behandlungspflege',
            'letter' => 'B',
            'summary' => 'Ärztlich verordnete medizinische Maßnahmen, die häufig zu Hause durchgeführt werden.',
            'intro' => 'Behandlungspflege ist ein Teil der häuslichen Krankenpflege. Dazu können zum Beispiel Medikamentengabe, Verbandswechsel, Injektionen oder das An- und Ausziehen von Kompressionsstrümpfen gehören.',
            'sections' => [
                ['title' => 'Was ist dafür notwendig?', 'body' => 'Die Maßnahme muss in der Regel ärztlich verordnet und von der Krankenkasse genehmigt werden. Ausgeführt wird sie beispielsweise von einem zugelassenen ambulanten Pflegedienst.'],
                ['title' => 'Nicht mit Grundpflege verwechseln', 'body' => 'Behandlungspflege dient einem medizinischen Behandlungsziel. Unterstützung beim Waschen, Essen oder Bewegen gehört dagegen zur körperbezogenen Pflege und folgt anderen Leistungsregeln.'],
            ],
            'tip' => 'Die ärztliche Verordnung frühzeitig an den Pflegedienst und die Krankenkasse weitergeben.',
            'sources' => [['label' => 'Bundesgesundheitsministerium: Häusliche Krankenpflege', 'url' => 'https://www.bundesgesundheitsministerium.de/haushaltshilfe/']],
            'related' => ['ambulante-pflege', 'pflegegrad'],
            'checked_at' => '2026-07-16',
        ],
        'entlastungsbetrag' => [
            'title' => 'Entlastungsbetrag',
            'letter' => 'E',
            'summary' => 'Zweckgebundene Unterstützung für anerkannte Entlastungs- und Betreuungsangebote.',
            'intro' => 'Der Entlastungsbetrag unterstützt pflegebedürftige Menschen in häuslicher Pflege und soll zugleich pflegende Angehörige entlasten. Er wird nicht automatisch als frei verfügbares Geld ausgezahlt.',
            'sections' => [
                ['title' => 'Wofür kann er genutzt werden?', 'body' => 'Möglich sind je nach Voraussetzung unter anderem anerkannte Angebote zur Unterstützung im Alltag, Tages- oder Nachtpflege, Kurzzeitpflege sowie bestimmte Leistungen zugelassener Pflege- oder Betreuungsdienste.'],
                ['title' => 'Wie erfolgt die Erstattung?', 'body' => 'Häufig werden Rechnungen und Nachweise bei der Pflegekasse eingereicht oder der Anbieter rechnet nach einer Abtretung direkt ab. Anerkennung und Abrechnung können sich nach Bundesland und Angebot unterscheiden.'],
            ],
            'tip' => 'Vor der Buchung fragen, ob das Angebot nach Landesrecht anerkannt ist und über den Entlastungsbetrag abgerechnet werden kann.',
            'sources' => [['label' => 'Bundesgesundheitsministerium: Entlastungsbetrag', 'url' => 'https://www.bundesgesundheitsministerium.de/pflege-zu-hause/weitere-leistungen-und-angebote-zur-unterstuetzung-im-alltag']],
            'related' => ['tagespflege', 'kurzzeitpflege', 'pflegegrad'],
            'checked_at' => '2026-07-16',
        ],
        'kurzzeitpflege' => [
            'title' => 'Kurzzeitpflege',
            'letter' => 'K',
            'summary' => 'Vorübergehende vollstationäre Pflege, wenn die Versorgung zu Hause zeitweise nicht ausreicht.',
            'intro' => 'Kurzzeitpflege kann helfen, wenn eine pflegebedürftige Person für begrenzte Zeit nicht zu Hause versorgt werden kann, etwa nach einem Krankenhausaufenthalt oder in einer Krisensituation.',
            'sections' => [
                ['title' => 'Wo findet sie statt?', 'body' => 'Die Versorgung erfolgt vorübergehend in einer dafür zugelassenen stationären Pflegeeinrichtung. Ein freier Platz muss direkt bei der Einrichtung angefragt werden.'],
                ['title' => 'Welche Kosten bleiben?', 'body' => 'Die Pflegeversicherung kann unter bestimmten Voraussetzungen pflegebedingte Aufwendungen übernehmen. Kosten für Unterkunft, Verpflegung und mögliche Investitionskosten können ganz oder teilweise selbst zu tragen sein.'],
            ],
            'tip' => 'Frühzeitig nach einem Platz, den Gesamtkosten und der Abrechnung über den gemeinsamen Jahresbetrag fragen.',
            'sources' => [['label' => 'Bundesgesundheitsministerium: Kurzzeitpflege', 'url' => 'https://www.bundesgesundheitsministerium.de/themen/pflege/online-ratgeber-pflege/leistungen-der-pflegeversicherung/leistungen-im-ueberblick/voruebergehende-vollstationaere-kurzzeitpflege']],
            'related' => ['verhinderungspflege', 'stationaere-pflege', 'pflegegrad'],
            'checked_at' => '2026-07-16',
        ],
        'pflegeberatung' => [
            'title' => 'Pflegeberatung',
            'letter' => 'P',
            'summary' => 'Persönliche Orientierung zu Pflegeleistungen, Anträgen und passenden Hilfen.',
            'intro' => 'Eine Pflegeberatung hilft dabei, den Unterstützungsbedarf zu klären, Leistungen zu verstehen und die nächsten Schritte zu planen. Beratung bieten unter anderem Pflegekassen und Pflegestützpunkte an.',
            'sections' => [
                ['title' => 'Wer hat Anspruch?', 'body' => 'Ein Beratungsanspruch besteht insbesondere für Menschen, die Pflegeleistungen erhalten, einen Antrag gestellt haben oder eine Begutachtung zur Feststellung der Pflegebedürftigkeit anstoßen möchten.'],
                ['title' => 'Was sollte vorbereitet werden?', 'body' => 'Hilfreich sind vorhandene Bescheide, ärztliche Unterlagen, eine Übersicht über den Alltag und konkrete Fragen zur Versorgung, Finanzierung oder Entlastung von Angehörigen.'],
            ],
            'tip' => 'Die Beratung kann schon vor der Entscheidung für einen Pflegedienst oder ein Pflegeheim genutzt werden.',
            'sources' => [['label' => 'Bundesgesundheitsministerium: Pflegeberatung', 'url' => 'https://www.bundesgesundheitsministerium.de/themen/pflege/online-ratgeber-pflege/pflegeberatung']],
            'related' => ['pflegegrad', 'pflegegeld', 'pflegesachleistung'],
            'checked_at' => '2026-07-16',
        ],
        'pflegegeld' => [
            'title' => 'Pflegegeld',
            'letter' => 'P',
            'summary' => 'Leistung der Pflegeversicherung bei selbst organisierter häuslicher Pflege.',
            'intro' => 'Pflegegeld kann gezahlt werden, wenn die häusliche Pflege zum Beispiel durch Angehörige, Freunde oder andere ehrenamtlich Pflegende sichergestellt wird. Es wird an die pflegebedürftige Person überwiesen.',
            'sections' => [
                ['title' => 'Welche Voraussetzung gilt?', 'body' => 'Pflegegeld setzt grundsätzlich einen entsprechenden Pflegegrad und eine sichergestellte häusliche Pflege voraus. Die pflegebedürftige Person entscheidet über die Verwendung.'],
                ['title' => 'Kann ein Pflegedienst zusätzlich helfen?', 'body' => 'Pflegegeld und ambulante Pflegesachleistungen können als Kombinationsleistung miteinander verbunden werden. Dann wird das Pflegegeld abhängig von den genutzten Sachleistungen anteilig berechnet.'],
            ],
            'tip' => 'Bei Pflegegeld sind in bestimmten Abständen Beratungsbesuche vorgesehen. Die Pflegekasse informiert über die persönliche Verpflichtung.',
            'sources' => [['label' => 'Bundesgesundheitsministerium: Pflegegeld', 'url' => 'https://www.bundesgesundheitsministerium.de/pflegegeld']],
            'related' => ['pflegegrad', 'pflegesachleistung', 'ambulante-pflege'],
            'checked_at' => '2026-07-16',
        ],
        'pflegegrad' => [
            'title' => 'Pflegegrad',
            'letter' => 'P',
            'summary' => 'Einstufung danach, wie stark Selbstständigkeit und Fähigkeiten beeinträchtigt sind.',
            'intro' => 'Die fünf Pflegegrade beschreiben, wie stark ein Mensch wegen gesundheitlicher Beeinträchtigungen auf Hilfe angewiesen ist. Entscheidend ist nicht nur eine Diagnose, sondern die Selbstständigkeit im Alltag.',
            'sections' => [
                ['title' => 'Wie wird der Pflegegrad festgestellt?', 'body' => 'Nach einem Antrag veranlasst die Pflegekasse eine Begutachtung. Bei gesetzlich Versicherten erfolgt sie in der Regel durch den Medizinischen Dienst; bei privat Versicherten durch Medicproof.'],
                ['title' => 'Warum ist er wichtig?', 'body' => 'Der festgestellte Pflegegrad beeinflusst, welche Leistungen der Pflegeversicherung grundsätzlich genutzt werden können. Der konkrete Anspruch hängt zusätzlich von der Versorgungsform und weiteren Voraussetzungen ab.'],
            ],
            'tip' => 'Vor der Begutachtung mehrere Tage notieren, wobei im Alltag Hilfe, Erinnerung oder Beaufsichtigung benötigt wird.',
            'sources' => [['label' => 'Bundesgesundheitsministerium: Pflegebedürftigkeit und Pflegegrade', 'url' => 'https://www.bundesgesundheitsministerium.de/themen/pflege/online-ratgeber-pflege/pflegebeduerftig-was-nun/pflegebeduerftigkeit']],
            'related' => ['pflegeberatung', 'pflegegeld', 'pflegesachleistung'],
            'checked_at' => '2026-07-16',
        ],
        'pflegehilfsmittel' => [
            'title' => 'Pflegehilfsmittel',
            'letter' => 'P',
            'summary' => 'Hilfsmittel, die Pflege erleichtern, Beschwerden lindern oder Selbstständigkeit fördern.',
            'intro' => 'Zu Pflegehilfsmitteln gehören technische Hilfen und zum Verbrauch bestimmte Produkte. Beispiele sind Pflegebetten, Hausnotrufsysteme oder bestimmte Schutz- und Hygieneprodukte.',
            'sections' => [
                ['title' => 'Wer ist zuständig?', 'body' => 'Die Pflegekasse kann Kosten übernehmen, wenn das Hilfsmittel der Pflege dient und nicht vorrangig die Krankenkasse zuständig ist. Manche technischen Hilfsmittel werden leihweise bereitgestellt.'],
                ['title' => 'Wie wird der Bedarf festgestellt?', 'body' => 'Ein Bedarf kann unter anderem bei der Pflegebegutachtung empfohlen werden. Auch Pflegefachpersonen können im Rahmen ihrer Befugnisse Hinweise geben. Die Entscheidung trifft der zuständige Kostenträger.'],
            ],
            'tip' => 'Vor einem privaten Kauf zuerst bei Pflege- oder Krankenkasse nach Antrag, Vertragspartnern und Kostenübernahme fragen.',
            'sources' => [['label' => 'Bundesgesundheitsministerium: Pflegehilfsmittel', 'url' => 'https://www.bundesgesundheitsministerium.de/pflege-zu-hause/pflegehilfsmittel']],
            'related' => ['pflegegrad', 'ambulante-pflege', 'pflegeberatung'],
            'checked_at' => '2026-07-16',
        ],
        'pflegesachleistung' => [
            'title' => 'Pflegesachleistung',
            'letter' => 'P',
            'summary' => 'Budget der Pflegeversicherung für Leistungen zugelassener ambulanter Dienste.',
            'intro' => 'Mit ambulanten Pflegesachleistungen kann ein zugelassener Pflege- oder Betreuungsdienst für die Versorgung zu Hause beauftragt werden. Der Dienst rechnet die vereinbarten Leistungen bis zum verfügbaren Höchstbetrag mit der Pflegekasse ab.',
            'sections' => [
                ['title' => 'Was kann dazugehören?', 'body' => 'Je nach Zulassung und Vertrag gehören dazu körperbezogene Pflegemaßnahmen, pflegerische Betreuung und Hilfen bei der Haushaltsführung. Nicht jede angebotene Leistung ist automatisch durch die Pflegeversicherung abgedeckt.'],
                ['title' => 'Was bedeutet Sachleistung?', 'body' => 'Der Begriff bedeutet nicht, dass Gegenstände geliefert werden. Gemeint sind professionelle Dienstleistungen. Nicht ausgeschöpfte Beträge werden grundsätzlich nicht vollständig als Geld ausgezahlt; eine anteilige Kombination mit Pflegegeld kann möglich sein.'],
            ],
            'tip' => 'Leistungskomplexe, Häufigkeit, private Zusatzkosten und Kündigungsregeln vorab schriftlich festhalten.',
            'sources' => [['label' => 'Bundesgesundheitsministerium: Ambulante Pflegesachleistungen', 'url' => 'https://www.bundesgesundheitsministerium.de/pflege-zu-hause/pflegesachleistungen']],
            'related' => ['ambulante-pflege', 'pflegegeld', 'pflegegrad'],
            'checked_at' => '2026-07-16',
        ],
        'stationaere-pflege' => [
            'title' => 'Stationäre Pflege',
            'letter' => 'S',
            'summary' => 'Dauerhafte Pflege und Betreuung in einer vollstationären Pflegeeinrichtung.',
            'intro' => 'Bei vollstationärer Pflege lebt die pflegebedürftige Person dauerhaft in einem Pflegeheim. Pflege, Betreuung, Unterkunft und Verpflegung werden an einem Ort organisiert.',
            'sections' => [
                ['title' => 'Wann kommt sie infrage?', 'body' => 'Stationäre Pflege kann passend sein, wenn eine sichere Versorgung zu Hause nicht mehr ausreichend organisiert werden kann oder eine Betreuung rund um die Uhr erforderlich ist. Die Entscheidung hängt von der persönlichen Situation ab.'],
                ['title' => 'Wie setzen sich die Kosten zusammen?', 'body' => 'Die Pflegeversicherung beteiligt sich abhängig vom Pflegegrad an pflegebedingten Aufwendungen. Unterkunft, Verpflegung, Investitionskosten und weitere Eigenanteile müssen gesondert betrachtet werden.'],
            ],
            'tip' => 'Vor einer Entscheidung das Haus besichtigen und einen vollständigen, persönlichen Kostenüberblick verlangen.',
            'sources' => [['label' => 'Bundesgesundheitsministerium: Pflegeeinrichtungen (stationär)', 'url' => 'https://www.bundesgesundheitsministerium.de/service/begriffe-von-a-z/p/pflegeheim']],
            'related' => ['kurzzeitpflege', 'pflegegrad', 'pflegeberatung'],
            'checked_at' => '2026-07-16',
        ],
        'tagespflege' => [
            'title' => 'Tagespflege',
            'letter' => 'T',
            'summary' => 'Zeitweise Betreuung in einer Einrichtung als Ergänzung zur Pflege zu Hause.',
            'intro' => 'Tagespflege ist eine teilstationäre Versorgung. Pflegebedürftige Menschen verbringen einen oder mehrere Tage pro Woche in einer Einrichtung und wohnen weiterhin zu Hause.',
            'sections' => [
                ['title' => 'Was bietet eine Tagespflege?', 'body' => 'Typisch sind pflegerische Unterstützung, Betreuung, gemeinsame Mahlzeiten und Aktivitäten. Die notwendige Beförderung zwischen Wohnung und Einrichtung kann Teil der Leistung sein.'],
                ['title' => 'Welche Kosten entstehen?', 'body' => 'Die Pflegekasse kann bei Vorliegen der Voraussetzungen pflegebedingte Aufwendungen bis zu einem Höchstbetrag übernehmen. Unterkunft, Verpflegung und Investitionskosten können zusätzlich berechnet werden.'],
            ],
            'tip' => 'Nach einem Kennenlerntag, verfügbaren Betreuungstagen, Fahrdienst und allen privaten Kosten fragen.',
            'sources' => [['label' => 'Bundesgesundheitsministerium: Teilstationäre Tages- oder Nachtpflege', 'url' => 'https://www.bundesgesundheitsministerium.de/themen/pflege/online-ratgeber-pflege/leistungen-der-pflegeversicherung/teilstationaere-pflege']],
            'related' => ['ambulante-pflege', 'entlastungsbetrag', 'pflegegrad'],
            'checked_at' => '2026-07-16',
        ],
        'verhinderungspflege' => [
            'title' => 'Verhinderungspflege',
            'letter' => 'V',
            'summary' => 'Zeitweise Ersatzpflege, wenn die private Pflegeperson verhindert ist.',
            'intro' => 'Verhinderungspflege kann genutzt werden, wenn eine Pflegeperson vorübergehend ausfällt, zum Beispiel wegen Urlaub, Krankheit oder eines Termins. Die Ersatzpflege kann stundenweise oder für mehrere Tage organisiert werden.',
            'sections' => [
                ['title' => 'Wer kann die Ersatzpflege übernehmen?', 'body' => 'Je nach Situation kommen ambulante Pflegedienste, Einzelpflegekräfte, ehrenamtlich Pflegende oder Angehörige infrage. Für nahe Angehörige und Personen im selben Haushalt gelten besondere Erstattungsregeln.'],
                ['title' => 'Was ist der gemeinsame Jahresbetrag?', 'body' => 'Verhinderungs- und Kurzzeitpflege greifen auf einen gemeinsamen Jahresbetrag zurück. Wer eine der Leistungen nutzt, verringert damit das im Kalenderjahr noch verfügbare Budget für beide Leistungsarten.'],
            ],
            'tip' => 'Vor der Planung den verbleibenden Betrag direkt bei der Pflegekasse erfragen und Rechnungen aufbewahren.',
            'sources' => [['label' => 'Bundesgesundheitsministerium: Verhinderungspflege', 'url' => 'https://www.bundesgesundheitsministerium.de/verhinderungspflege/seite']],
            'related' => ['kurzzeitpflege', 'pflegegeld', 'ambulante-pflege'],
            'checked_at' => '2026-07-16',
        ],
        ...(require __DIR__.'/lexicon-additional.php'),
    ],
];
